# Generated by Django 5.0.6 on 2024-07-02 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habit', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NiceHabit',
        ),
    ]
