# Generated by Django 5.0.6 on 2024-07-02 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habit", "0002_delete_nicehabit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="is_nice_habit",
            field=models.BooleanField(
                default=False, help_text="Признак приятной привычки"
            ),
        ),
    ]
